$schema: https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#
contentVersion: 1.0.0.0

parameters:
  name:
    type: string
    metadata:
      description: Name of the Application Insights.

  locationCode:
    type: string
    metadata:
      description: Location code where the resource is provisioned.

  kind:
    type: string
    metadata:
      description: The type of Application Insights instance.
    allowedValues:
    - other
    - web
    defaultValue: web

  # ADMIN PARAMETERS - DO NOT TOUCH
  locationLookup:
    type: object
    metadata:
      description: The reference to lookup location - DO NOT TOUCH
    defaultValue:
      auc: australiacentral
      aue: australiaeast
      ause: australiasoutheast
      jpe: japaneast
      jpw: japanwest
      krc: koreacentral
      krs: koreasouth
      ea: eastasia
      sea: southeastasia

  author:
    type: string
    metadata:
      description: Author in tags
    defaultValue: Justin Yoo
  profile:
    type: string
    metadata:
      description: Profile in tags
    defaultValue: https://twitter.com/justinchronicle
  projectUrl:
    type: string
    metadata:
      description: Project URL in tags
    defaultValue: https://github.com/devkimchi/Key-Vault-Backup-Restore-Sample
  repositoryUrl:
    type: string
    metadata:
      description: Repository URL in tags
    defaultValue: https://github.com/devkimchi/Key-Vault-Backup-Restore-Sample
  license:
    type: string
    metadata:
      description: License in tags
    defaultValue: https://raw.githubusercontent.com/devkimchi/Key-Vault-Backup-Restore-Sample/master/LICENSE

variables:
  # METADATA
  location: "[if(contains(parameters('locationLookup'), parameters('locationCode')), parameters('locationLookup')[parameters('locationCode')], resourceGroup().location)]"

  # RESOURCE SPECIFIC VARIABLES
  appInsights:
    name: "[parameters('name')]"
    apiVersion: "[providers('Microsoft.Insights', 'components').apiVersions[0]]"
    location: "[variables('location')]"
    kind: "[parameters('kind')]"

  # TAGS
  tags:
    author: "[parameters('author')]"
    profile: "[parameters('profile')]"
    projectUrl: "[parameters('projectUrl')]"
    repositoryUrl: "[parameters('repositoryUrl')]"
    license: "[parameters('license')]"

resources:
- comments: "### RESOURCE - APPLICATION INSIGHTS ###"
  type: Microsoft.Insights/components
  apiVersion: "[variables('appInsights').apiVersion]"
  name: "[variables('appInsights').name]"
  location: "[variables('appInsights').location]"
  kind: "[variables('appInsights').kind]"
  tags: "[variables('tags')]"
  properties:
    applicationId: "[variables('appInsights').name]"

outputs: {}
